version: '3.8'

name: main_app_test_image
services:
  my_web_app:
    build:
      dockerfile: test.Dockerfile
    container_name: mainapp-web-test
    env_file:
      - .docker.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: pytest

  db:
    image: postgres:15.1-alpine
    container_name: mainapp-db-test
    restart: always
    expose:
      - 5432
    env_file:
      - .docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 20

  redis:
    image: redis:latest
    container_name: menuapp-cache-test
    restart: always
    env_file:
      - .docker.env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
