version: '3.8'

name: menu_app_test_image
services:
  my_web_app:
    build:
      dockerfile: test.Dockerfile
    container_name: mainapp-web-test
    env_file:
      - .docker.env
    volumes:
      - excel_volume:/taskworker/admin
      - json_volume:/taskworker/output
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: pytest

  db:
    image: postgres:15.1-alpine
    container_name: mainapp-db-test
    restart: always
    expose:
      - 5432
    env_file:
      - .docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 20

  redis:
    image: redis:latest
    container_name: mainapp-cache-test
    restart: always
    env_file:
      - .docker.env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30


  celery:
    build:
      dockerfile: celery.Dockerfile
    restart: always
    container_name: mainapp-celery-web-test
    env_file:
      - .docker.env
    volumes:
      - excel_volume:/taskworker/admin
      - json_volume:/taskworker/output
    expose:
      - 5672
      - 8000
    command: celery -A taskworker.main worker -B --loglevel=INFO --pool=solo
    depends_on:
      rabbitmq:
        condition: service_healthy
      my_web_app:
        condition: service_started

  rabbitmq:
    image: rabbitmq:latest
    container_name: mainapp-rabbitmq-test
    expose:
      - 5672
      - 15672
    env_file:
      - .docker.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3

volumes:
  excel_volume:
  json_volume:
